name: Publicar Pagina a Surge.sh

on:
  push:
    branches:
      - master  # Esta es la rama que debe hacer el push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Instalar Surge
        run: npm install --global surge

      - name: Publicar pagina
        run: surge --project ./ --domain claudioferreira20100316.surge.sh --token ac67c11a200fd2c3f2ecfae915b39b4a